### PR TITLE
Implemented support for firebird database:

### PR DESCRIPTION
**Pull request by nmm**
- included FirebirdSql.Data.FirebirdClient as nuget package
- updated target framework to 4.5.2

Fixed bug: file handle not closed when table empty
Improvement: Added quoting when CR/LF exists
Improvement: Cursor.Wait while exporting

### CODE REVIEW

**Comment by flipm0de** [comment]
Please correct the formatting of the code to match the one used in the project (spaces, braces position, new lines).
Are these changes:
"Fixed bug: file handle not closed when table empty
Improvement: Added quoting when CR/LF exists
Improvement: Cursor.Wait while exporting"
related only to the new code you are adding now?

**Comment by nmm** [comment]
> Are these changes related only to the new code you are adding now?

yes, it is included: 
- not closed file handle fix in MainForm.cs btnExport_Click: 
`if (!reader.Read ())
                            {
                                exportProvider.FinishExport ();
                                continue;
                            }`
- quote around strings with CR/LF - change is the only one in SVExportProviderBase.cs
- not closed file handle fix in MainForm.cs btnExport_Click: 
` Cursor.Current = Cursors.WaitCursor;
            try
{ ... }
finally
            {
                Cursor.Current = Cursors.Default;
            }`

code formatting is committed.

**Comment by flipm0de** [comment]
Please fix the formatting for your changes in the MainForm.cs file too.

**Comment by nmm** [comment]
Done

**Pull request merged**
